//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ffjoin.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ffjoin.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string COLUMN_DATE {
            get {
                return ResourceManager.GetString("COLUMN_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        internal static string COLUMN_DURATION {
            get {
                return ResourceManager.GetString("COLUMN_DURATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ext.
        /// </summary>
        internal static string COLUMN_EXTENTION {
            get {
                return ResourceManager.GetString("COLUMN_EXTENTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string COLUMN_FILE {
            get {
                return ResourceManager.GetString("COLUMN_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose ffmpeg.
        /// </summary>
        internal static string S_CHOOSE_FFMPEG {
            get {
                return ResourceManager.GetString("S_CHOOSE_FFMPEG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File extensions are different..
        /// </summary>
        internal static string S_DIFFERENT_EXTENSION {
            get {
                return ResourceManager.GetString("S_DIFFERENT_EXTENSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to open created video?.
        /// </summary>
        internal static string S_DO_YOU_WANT_TO_OPEN_CREATED_VIDEO {
            get {
                return ResourceManager.GetString("S_DO_YOU_WANT_TO_OPEN_CREATED_VIDEO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration of input video files.
        /// </summary>
        internal static string S_DURATION_OF_INPUTFILES {
            get {
                return ResourceManager.GetString("S_DURATION_OF_INPUTFILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration of output video file.
        /// </summary>
        internal static string S_DURATION_OUTPUT {
            get {
                return ResourceManager.GetString("S_DURATION_OUTPUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} does not exist..
        /// </summary>
        internal static string S_FILE_NOT_EXISTS {
            get {
                return ResourceManager.GetString("S_FILE_NOT_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save to ini.
        /// </summary>
        internal static string S_INISAVE_FAILED {
            get {
                return ResourceManager.GetString("S_INISAVE_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It needs at least two files to join..
        /// </summary>
        internal static string S_LESSTHAN_TWO_ITEMS {
            get {
                return ResourceManager.GetString("S_LESSTHAN_TWO_ITEMS", resourceCulture);
            }
        }
    }
}
